name: Blog CI/CD

# 触发条件：在 push 到 main 分支后触发
on:
  push:
    branches: 
      - main

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v3
      with: 
        submodules: recursive

    - name: Setup node
      # 设置 node.js 环境
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install hexo dependencies
      # 下载 hexo-cli 脚手架及相关安装包
      run: |
        npm install -g hexo-cli
        npm install hexo-deployer-git --save
        npm install
        
    - name: Setup ssh-private-key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        
    - name: Generate & Deploy files
      # 编译 markdown 文件
      run: |
        git config --global init.defaultBranch main
        git config --global user.email "${{ secrets.USER_EMAIL }}"
        git config --global user.name "${{ secrets.USER_NAME }}"
        hexo g -d
